name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5

    - name: Install dune
      run: |
        opam install dune

    - name: Install dependencies
      run: |
        eval $(opam env)
        opam install cohttp cohttp-lwt cohttp-lwt-unix lwt lwt_ssl yojson uuidm logs base64 cmdliner fmt result
        opam install alcotest alcotest-lwt ocamlformat

    - name: Build
      run: |
        eval $(opam env)
        dune build

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest

    - name: Check formatting
      run: |
        eval $(opam env)
        dune build @fmt

    - name: Build documentation
      run: |
        eval $(opam env)
        dune build @doc

  lint-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-doc@v3

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-fmt@v3

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-opam@v3
