name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ocaml-version: [5.1.0, 5.2.0, 5.3.0]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use OCaml ${{ matrix.ocaml-version }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
        
    - name: Install dependencies
      run: |
        opam update
        opam install . --deps-only --with-test --with-dev
        
    - name: Build
      run: dune build
      
    - name: Run tests
      run: dune runtest
      
    - name: Check formatting
      run: dune build @fmt
      
    - name: Build documentation
      run: dune build @doc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use OCaml 5.3.0
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.3.0
        
    - name: Install dependencies
      run: |
        opam update
        opam install . --deps-only --with-test --with-dev
        
    - name: Check code formatting
      run: dune build @fmt
      
    - name: Check for unused dependencies
      run: dune external-lib-deps --missing
