name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5

    - name: Install dune
      run: |
        opam install dune

    - name: Install dependencies
      run: |
        eval $(opam env)
        opam install cohttp cohttp-lwt cohttp-lwt-unix lwt lwt_ssl yojson uuidm logs base64 cmdliner fmt result
        opam install alcotest alcotest-lwt ocamlformat

    - name: Build
      run: |
        eval $(opam env)
        dune build

    - name: Check formatting
      run: |
        eval $(opam env)
        dune build @fmt

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest
